CREATE TABLE [dbo].[Commentary]
(
	[Id] INT IDENTITY PRIMARY KEY,
	[DishId] INT NOT NULL REFERENCES [Dish], 
	[UserId] INT NULL REFERENCES [User] ON DELETE SET NULL,
	[Content] NVARCHAR(MAX) NULL,
	[Rating] DECIMAL(2, 1) NOT NULL,
	[Date] DATETIME2 NOT NULL DEFAULT GETDATE()
)
