CREATE TABLE [dbo].[User]
(
	[Id] INT IDENTITY PRIMARY KEY,
	[Email] NVARCHAR(255) NOT NULL UNIQUE,
	[Password] VARBINARY(MAX) NOT NULL,
	[Role] NVARCHAR(50) NOT NULL DEFAULT 'CUSTOMER',
	[LastName] NVARCHAR(100) NOT NULL,
	[FirstName] NVARCHAR(100) NOT NULL,
	[Street] NVARCHAR(255) NOT NULL,
	[Number] NVARCHAR(10) NULL,
	[ZipCode] INT NOT NULL,
	[City] VARCHAR(100) NOT NULL,
	[BirthDate] DateTime2 NULL
)
